services:
  - type: web
    name: synapse-labs
    env: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
