services:
  - type: web
    name: synapse-labs
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - next.config.js
        - tsconfig.json
        - postcss.config.js
        - tailwind.config.js
